import { Award, Clock, Heart, Users } from "lucide-react";

export const menuItems = [
    { name: 'Catálogo', href: '#catalogo' },
    { name: 'Tortas Personalizadas', href: '#personalizadas' },
    { name: 'Sobre Nosotros', href: '#nosotros' },
    { name: 'Contacto', href: '#contacto' },
  ];

export const mapLinkLocation = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d9741.95423283405!2d-73.62713402394917!3d4.144882349018321!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e3e2dd8efa16017%3A0x8ff16219e6d31841!2sCra.%2020%20%23%2025C-36%2C%20Villavicencio%2C%20Meta%2C%20Colombia!5e0!3m2!1ses-419!2sar!4v1767208713473!5m2!1ses-419!2sar";

export const quickFilters = ['Hoy', 'Cumpleaños', 'Regalo', 'Sin TACC', 'Vegano'];

export const stats = [
  { icon: Heart, value: '500+', label: 'Clientes felices' },
  { icon: Award, value: '4 años', label: 'De experiencia' },
  { icon: Users, value: '1000+', label: 'Tortas creadas' },
  { icon: Clock, value: '24/7', label: 'Atención online' },
];

export const SERVINGS_OPTIONS = [
  { value: "10", label: "10 porciones" },
  { value: "15", label: "15 porciones" },
  { value: "20", label: "20 porciones" },
  { value: "30", label: "30 porciones" },
  { value: "40", label: "40 porciones" },
  { value: "50+", label: "50+ porciones" },
];

export const FLAVOR_OPTIONS = [
  { value: "", label: "Selecciona un sabor" },
  { value: "Vainilla", label: "Vainilla" },
  { value: "Chocolate", label: "Chocolate" },
  { value: "Red Velvet", label: "Red Velvet" },
  { value: "Limón", label: "Limón" },
  { value: "Zanahoria", label: "Zanahoria" },
  { value: "Café", label: "Café" },
];

export const FILLING_OPTIONS = [
  { value: "", label: "Selecciona un relleno" },
  { value: "Dulce de Leche", label: "Dulce de Leche" },
  { value: "Crema Chantilly", label: "Crema Chantilly" },
  { value: "Mousse de Chocolate", label: "Mousse de Chocolate" },
  { value: "Frutas Frescas", label: "Frutas Frescas" },
  { value: "Crema Pastelera", label: "Crema Pastelera" },
  { value: "Nutella", label: "Nutella" },
];

export const GALLERY_IMAGES_INFO = [
  "/beauty_cake.jpg",
  "/beers_cake.jpg",
  "/car_cake.jpg",
  "/coronabeer_cake.jpg",
];

export const WHY_CHOOSE_OPTIONS = [
  'Ingredientes de primera calidad',
  'Diseños 100% personalizados',
  'Entrega puntual garantizada',
  'Más de 500 clientes satisfechos',
  'Opciones sin TACC y veganas',
];


export const productsByCategory = {
  tortas: [
    {
      id: 1,
      name: 'Torta Red Velvet',
      price: '$45.000',
      image: '/tortas_1.jpeg',
      tags: ['Más vendido', 'Nuevo'],
    },
    {
      id: 3,
      name: 'Torta de Chocolate Premium',
      price: '$48.000',
      image: '/tortas_3.jpeg',
      tags: [],
    },
    {
      id: 4,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_4.jpeg',
      tags: [],
    },
    {
      id: 5,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_5.jpeg',
      tags: [],
    },
    {
      id: 6,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_6.jpeg',
      tags: [],
    },
    {
      id: 7,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_7.jpeg',
      tags: [],
    },
    {
      id: 8,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_8.jpeg',
      tags: [],
    },
    {
      id: 9,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_9.jpeg',
      tags: [],
    },
    {
      id: 10,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_10.jpeg',
      tags: [],
    },
    {
      id: 11,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_11.jpeg',
      tags: [],
    },
    {
      id: 12,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_12.jpeg',
      tags: [],
    },
    {
      id: 13,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_13.jpeg',
      tags: [],
    },
    {
      id: 14,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_14.jpeg',
      tags: [],
    },
    {
      id: 15,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_15.jpeg',
      tags: [],
    },
    {
      id: 16,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_16.jpeg',
      tags: [],
    },
    {
      id: 17,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_17.jpeg',
      tags: [],
    },
    {
      id: 18,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_18.jpeg',
      tags: [],
    },
    {
      id: 19,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_19.jpeg',
      tags: [],
    },
    {
      id: 20,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_20.jpeg',
      tags: [],
    },
    {
      id: 21,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_21.jpeg',
      tags: [],
    },
    {
      id: 22,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_22.jpeg',
      tags: [],
    },
    {
      id: 23,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_23.jpeg',
      tags: [],
    },
    {
      id: 24,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_24.jpeg',
      tags: [],
    },
    {
      id: 25,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_25.jpeg',
      tags: [],
    },
    {
      id: 26,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_26.jpeg',
      tags: [],
    },
    {
      id: 27,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_27.jpeg',
      tags: [],
    },
    {
      id: 28,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_28.jpeg',
      tags: [],
    },
    {
      id: 29,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_29.jpeg',
      tags: [],
    },
    {
      id: 30,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_30.jpeg',
      tags: [],
    },
    {
      id: 31,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_31.jpeg',
      tags: [],
    },
    {
      id: 32,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_32.jpeg',
      tags: [],
    },
    {
      id: 33,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_33.jpeg',
      tags: [],
    },
    {
      id: 34,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_34.jpeg',
      tags: [],
    },
    {
      id: 35,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_35.jpeg',
      tags: [],
    },
    {
      id: 36,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_36.jpeg',
      tags: [],
    },
    {
      id: 37,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_37.jpeg',
      tags: [],
    },
    { 
      id: 38,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_38.jpeg',
      tags: [],
    },
    {
      id: 39,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_39.jpeg',
      tags: [],
    },
    {
      id: 40,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_40.jpeg',
      tags: [],
    },
    {
      id: 41,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_41.jpeg',
      tags: [],
    },
    {
      id: 42,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_42.jpeg',
      tags: [],
    },
    {
      id: 43,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_43.jpeg',
      tags: [],
    },
    {
      id: 44,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_44.jpeg',
      tags: [],
    },
    {
      id: 45,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_45.jpeg',
      tags: [],
    },
    {
      id: 46,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_46.jpeg',
      tags: [],
    },
    {
      id: 47,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_47.jpeg',
      tags: [],
    },
        {
      id: 48,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/tortas_48.jpeg',
      tags: [],
    }
  ],
  cupcakes: [
    {
      id: 49,
      name: 'Cupcakes Vainilla',
      price: '$3.500',
      image: '/cupcakes_1.jpeg',
      tags: ['Más vendido'],
    },
    {
      id: 50,
      name: 'Cupcakes Red Velvet',
      price: '$4.000',
      image: '/cupcakes_2.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 51,
      name: 'Cupcakes de Chocolate',
      price: '$3.800',
      image: '/cupcakes_3.jpeg',
      tags: [],
    },
    {
      id: 52,
      name: 'Cupcakes de Chocolate',
      price: '$3.800',
      image: '/cupcakes_4.jpeg',
      tags: [],
    },
    {
      id: 53,
      name: 'Cupcakes de Chocolate',
      price: '$3.800',
      image: '/cupcakes_5.jpeg',
      tags: [],
    },
  ],
  galletas: [
    {
      id: 54,
      name: 'Cookies Doble Chocolate',
      price: '$1.800',
      image: '/cookies_1.jpeg',
      tags: ['Más vendido'],
    },
    {
      id: 55,
      name: 'Cookies de Avena',
      price: '$1.500',
      image: '/cookies_2.jpeg',
      tags: [],
    },
    {
      id: 56,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/cookies_3.jpeg',
      tags: [],
    },
    {
      id: 57,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/cookies_4.jpeg',
      tags: [],
    },
    {
      id: 58,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/cookies_5.jpeg',
      tags: [],
    },
    {
      id: 59,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/cookies_6.jpeg',
      tags: [],
    },
  ],
  merengues: [
    {
      id: 60,
      name: 'Merengues Clásicos',
      price: '$1.200',
      image: '/merengues_1.jpeg',
      tags: [],
    },
    {
      id: 61,
      name: 'Merengues de Colores',
      price: '$1.400',
      image: '/merengues_2.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 62,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/merengues_3.jpeg',
      tags: ['Nuevo'],
    },
  ],
};

export const categoryInfo = {
  tortas: {
    title: 'Tortas',
    description: 'Tortas artesanales para cada ocasión especial',
    color: '#FFD1DC',
  },
  cupcakes: {
    title: 'Cupcakes',
    description: 'Pequeñas delicias perfectas para compartir',
    color: '#FFDAB9',
  },
  galletas: {
    title: 'Galletas',
    description: 'Galletas crujientes con ingredientes premium',
    color: '#E6E6FA',
  },
  merengues: {
    title: 'Merengues',
    description: 'Suaves y dulces, derriten en tu boca',
    color: '#FFE4E1',
  },
};