import { Award, Clock, Heart, Users } from "lucide-react";

export const menuItems = [
    { name: 'Catálogo', href: '#catalogo' },
    { name: 'Tortas Personalizadas', href: '#personalizadas' },
    { name: 'Sobre Nosotros', href: '#nosotros' },
    { name: 'Contacto', href: '#contacto' },
  ];

export const mapLinkLocation = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d9741.95423283405!2d-73.62713402394917!3d4.144882349018321!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e3e2dd8efa16017%3A0x8ff16219e6d31841!2sCra.%2020%20%23%2025C-36%2C%20Villavicencio%2C%20Meta%2C%20Colombia!5e0!3m2!1ses-419!2sar!4v1767208713473!5m2!1ses-419!2sar";

export const getWhatsappUrl = (text: string) => {
    return `https://wa.me/573123052735?text=${encodeURIComponent(text)}`;
  };

export const quickFilters = ['Cumpleaños', 'Regalos', 'Fechas especiales', 'Postres', 'Mesas dulces', 'Merengues'];

export const stats = [
  { icon: Heart, value: '500+', label: 'Clientes felices' },
  { icon: Award, value: '10 años', label: 'De experiencia' },
  { icon: Users, value: '1000+', label: 'Tortas creadas' },
  { icon: Clock, value: 'Atención online', label: 'Horario de oficina' },
];

export const SERVINGS_OPTIONS = [
  { value: "10", label: "10 porciones" },
  { value: "15", label: "15 porciones" },
  { value: "20", label: "20 porciones" },
  { value: "30", label: "30 porciones" },
  { value: "40", label: "40 porciones" },
  { value: "50+", label: "50+ porciones" },
];

export const FLAVOR_OPTIONS = [
  { value: "", label: "Selecciona un sabor" },
  { value: "Vainilla", label: "Vainilla" },
  { value: "Chocolate", label: "Chocolate" },
  { value: "Marmolada", label: "Marmolada" },
  { value: "Red Velvet", label: "Red Velvet" },
  { value: "Amapola", label: "Amapola" },
  { value: "Zanahoria", label: "Zanahoria" },
  { value: "Ponqué Colombiano", label: "Ponqué Colombiano" },
  { value: "Milky way", label: "Milky way" },
  { value: "Torta fría", label: "Torta fría" },
  { value: "Otras", label: "Otras" },
];

export const FILLING_OPTIONS = [
  { value: "", label: "Selecciona un relleno" },
  { value: "Crema de Limón", label: "Crema de Limón" },
  { value: "Crema de Maracuyá", label: "Crema de Maracuyá" },
  { value: "Ganache de Chocolate", label: "Ganache de Chocolate" },
  { value: "Dulce de Leche", label: "Dulce de Leche" },
  { value: "Mermelada casera", label: "Mermelada casera" },
  { value: "Crema Pastelera", label: "Crema Pastelera" },
  { value: "Otros", label: "Otros" },
];

export const GALLERY_IMAGES_INFO = [
  "/tortas_3.jpeg",
  "/cupcakes_1.jpeg",
  "/cupcakes_2.jpeg",
  "/tortas_4.jpeg",
];

export const WHY_CHOOSE_OPTIONS = [
  'Diseños 100% personalizados',
  'Entrega puntual garantizada',
  'Más de 500 clientes satisfechos',
  'Ingredientes de primera calidad',
];


export const productsByCategory = {
  tortas_cumpleaños: [
    {
      id: 1,
      name: 'Torta Red Velvet',
      price: '$45.000',
      image: '/cumpleaños_1.jpeg',
      tags: ['Más vendido', 'Nuevo'],
    },
    {
      id: 2,
      name: 'Torta de Chocolate Premium',
      price: '$48.000',
      image: '/cumpleaños_2.jpeg',
      tags: [],
    },
    {
      id: 3,
      name: 'Torta de Chocolate Premium',
      price: '$48.000',
      image: '/cumpleaños_3.jpeg',
      tags: [],
    },
    {
      id: 4,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/cumpleaños_4.jpeg',
      tags: [],
    },
    {
      id: 5,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/cumpleaños_5.jpeg',
      tags: [],
    },
    {
      id: 6,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/cumpleaños_6.jpeg',
      tags: [],
    },
    {
      id: 7,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/cumpleaños_7.jpeg',
      tags: [],
    },
    {
      id: 8,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/cumpleaños_8.jpeg',
      tags: [],
    },
    {
      id: 9,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/cumpleaños_9.jpeg',
      tags: [],
    },
    {
      id: 10,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/cumpleaños_10.jpeg',
      tags: [],
    },
    {
      id: 11,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/cumpleaños_11.jpeg',
      tags: [],
    }
  ],
    tortas_bodas: [
    {
      id: 13,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/bodas_1.jpeg',
      tags: [],
    },
    {
      id: 14,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/bodas_2.jpeg',
      tags: [],
    },
    {
      id: 15,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/bodas_3.jpeg',
      tags: [],
    },
    {
      id: 16,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/bodas_4.jpeg',
      tags: [],
    },
    {
      id: 17,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/bodas_5.jpeg',
      tags: [],
    },
    {
      id: 18,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/bodas_6.jpeg',
      tags: [],
    },
    {
      id: 19,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/bodas_7.jpeg',
      tags: [],
    },
  ],
  tortas_infantiles: [
    {
      id: 20,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_1.jpeg',
      tags: [],
    },
    {
      id: 21,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_2.jpeg',
      tags: [],
    },
    {
      id: 22,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_3.jpeg',
      tags: [],
    },
    {
      id: 23,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_4.jpeg',
      tags: [],
    },
    {
      id: 24,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_5.jpeg',
      tags: [],
    },
    {
      id: 25,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_6.jpeg',
      tags: [],
    },
    {
      id: 26,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_7.jpeg',
      tags: [],
    },
    {
      id: 27,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_8.jpeg',
      tags: [],
    },
    {
      id: 28,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_9.jpeg',
      tags: [],
    },
    {
      id: 29,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_10.jpeg',
      tags: [],
    },
    {
      id: 30,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_11.jpeg',
      tags: [],
    },
    {
      id: 31,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_12.jpeg',
      tags: [],
    },
    {
      id: 32,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_13.jpeg',
      tags: [],
    },
    {
      id: 33,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_14.jpeg',
      tags: [],
    },
    {
      id: 34,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_15.jpeg',
      tags: [],
    },
    {
      id: 35,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_16.jpeg',
      tags: [],
    },
    {
      id: 36,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_17.jpeg',
      tags: [],
    },
    {
      id: 37,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_18.jpeg',
      tags: [],
    },
    {
      id: 38,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_19.jpeg',
      tags: [],
    },
    {
      id: 39,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_20.jpeg',
      tags: [],
    },
    { 
      id: 40,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_21.jpeg',
      tags: [],
    },
    {
      id: 41,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_22.jpeg',
      tags: [],
    },
    {
      id: 42,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/infantiles_23.jpeg',
      tags: [],
    },
  ],
  tortas_grados: [
    {
      id: 43,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/grados_1.jpeg',
      tags: [],
    },
    {
      id: 44,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/grados_2.jpeg',
      tags: [],
    },
    {
      id: 45,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/grados_3.jpeg',
      tags: [],
    },
    {
      id: 46,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/grados_4.jpeg',
      tags: [],
    },
    {
      id: 47,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/grados_5.jpeg',
      tags: [],
    },
    {
      id: 48,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/grados_6.jpeg',
      tags: [],
    },
    {
      id: 49,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/grados_7.jpeg',
      tags: [],
    },
    {
      id: 50,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/grados_8.jpeg',
      tags: [],
    },
    {
      id: 51,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/grados_9.jpeg',
      tags: [],
    },
    {
      id: 52,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/grados_10.jpeg',
      tags: [],
    },
    {
      id: 53,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/grados_11.jpeg',
      tags: [],
    },
    {
      id: 54,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/grados_12.jpeg',
      tags: [],
    },
  ],
  tortas_bautizos: [
    {
      id: 55,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/bautizos_1.jpeg',
      tags: [],
    },
    {
      id: 56,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/bautizos_2.jpeg',
      tags: [],
    },
    {
      id: 57,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/bautizos_3.jpeg',
      tags: [],
    },
    {
      id: 58,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/bautizos_4.jpeg',
      tags: [],
    },
    {
      id: 59,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/bautizos_5.jpeg',
      tags: [],
    },
    {
      id: 60,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/bautizos_6.jpeg',
      tags: [],
    }
  ],
  otros: [
    {
      id: 61,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/otros_1.jpeg',
      tags: [],
    },
    {
      id: 62,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/otros_2.jpeg',
      tags: [],
    },
    {
      id: 63,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/otros_3.jpeg',
      tags: [],
    },
    {
      id: 64,
      name: 'Torta de Zanahoria',
      price: '$40.000',
      image: '/otros_4.jpeg',
      tags: [],
    },
  ],
  tortas_postres: [
    {
      id: 65,
      name: 'Cupcakes Vainilla',
      price: '$3.500',
      image: '/postres_1.jpeg',
      tags: ['Más vendido'],
    },
    {
      id: 66,
      name: 'Cupcakes Red Velvet',
      price: '$4.000',
      image: '/postres_2.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 67,
      name: 'Cupcakes de Chocolate',
      price: '$3.800',
      image: '/postres_3.jpeg',
      tags: [],
    },
    {
      id: 68,
      name: 'Cupcakes de Chocolate',
      price: '$3.800',
      image: '/postres_4.jpeg',
      tags: [],
    },
    {
      id: 69,
      name: 'Cupcakes de Chocolate',
      price: '$3.800',
      image: '/postres_5.jpeg',
      tags: [],
    },
    {
      id: 70,
      name: 'Cupcakes de Chocolate',
      price: '$3.800',
      image: '/postres_6.jpeg',
      tags: [],
    },
    {
      id: 71,
      name: 'Cupcakes de Chocolate',
      price: '$3.800',
      image: '/postres_7.jpeg',
      tags: [],
    },
    {
      id: 72,
      name: 'Cupcakes de Chocolate',
      price: '$3.800',
      image: '/postres_8.jpeg',
      tags: [],
    },
    {
      id: 73,
      name: 'Cupcakes de Chocolate',
      price: '$3.800',
      image: '/postres_9.jpeg',
      tags: [],
    },
    {
      id: 74,
      name: 'Cupcakes de Chocolate',
      price: '$3.800',
      image: '/postres_10.jpeg',
      tags: [],
    }
  ],
  mesas_dulces: [
    {
      id: 75,
      name: 'Cookies Doble Chocolate',
      price: '$1.800',
      image: '/dulces_1.jpeg',
      tags: ['Más vendido'],
    },
    {
      id: 76,
      name: 'Cookies de Avena',
      price: '$1.500',
      image: '/dulces_2.jpeg',
      tags: [],
    },
    {
      id: 77,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/dulces_3.jpeg',
      tags: [],
    },
    {
      id: 78,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/dulces_4.jpeg',
      tags: [],
    },
    {
      id: 79,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/dulces_5.jpeg',
      tags: [],
    },
    {
      id: 80,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/dulces_6.jpeg',
      tags: [],
    },
    {
      id: 81,
      name: 'Merengues Clásicos',
      price: '$1.200',
      image: '/dulces_7.jpeg',
      tags: [],
    },
    {
      id: 82,
      name: 'Merengues de Colores',
      price: '$1.400',
      image: '/dulces_8.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 83,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_9.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 84,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_10.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 85,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_11.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 86,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_12.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 87,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_13.jpeg',
      tags: ['Nuevo'],
    },
        {
      id: 88,
      name: 'Cookies Doble Chocolate',
      price: '$1.800',
      image: '/dulces_14.jpeg',
      tags: ['Más vendido'],
    },
    {
      id: 89,
      name: 'Cookies de Avena',
      price: '$1.500',
      image: '/dulces_15.jpeg',
      tags: [],
    },
    {
      id: 90,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/dulces_16.jpeg',
      tags: [],
    },
    {
      id: 91,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/dulces_17.jpeg',
      tags: [],
    },
    {
      id: 92,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/dulces_18.jpeg',
      tags: [],
    },
    {
      id: 93,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/dulces_19.jpeg',
      tags: [],
    },
    {
      id: 94,
      name: 'Merengues Clásicos',
      price: '$1.200',
      image: '/dulces_20.jpeg',
      tags: [],
    },
    {
      id: 95,
      name: 'Merengues de Colores',
      price: '$1.400',
      image: '/dulces_21.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 96,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_22.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 97,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_23.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 98,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_24.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 99,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_25.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 100,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_26.jpeg',
      tags: ['Nuevo'],
    },
        {
      id: 101,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/dulces_27.jpeg',
      tags: [],
    },
    {
      id: 102,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/dulces_28.jpeg',
      tags: [],
    },
    {
      id: 103,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/dulces_29.jpeg',
      tags: [],
    },
    {
      id: 104,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/dulces_30.jpeg',
      tags: [],
    },
    {
      id: 105,
      name: 'Merengues Clásicos',
      price: '$1.200',
      image: '/dulces_31.jpeg',
      tags: [],
    },
    {
      id: 106,
      name: 'Merengues de Colores',
      price: '$1.400',
      image: '/dulces_32.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 107,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_33.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 108,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_34.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 109,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_35.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 110,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_36.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 111,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/dulces_37.jpeg',
      tags: ['Nuevo'],
    },
  ],
  regalos: [
    {
      id: 112,
      name: 'Cookies Doble Chocolate',
      price: '$1.800',
      image: '/regalos_1.jpeg',
      tags: ['Más vendido'],
    },
    {
      id: 113,
      name: 'Cookies de Avena',
      price: '$1.500',
      image: '/regalos_2.jpeg',
      tags: [],
    },
    {
      id: 114,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/regalos_3.jpeg',
      tags: [],
    },
    {
      id: 115,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/regalos_4.jpeg',
      tags: [],
    },
    {
      id: 116,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/regalos_5.jpeg',
      tags: [],
    },
    {
      id: 117,
      name: 'Cookies de Mantequilla',
      price: '$1.600',
      image: '/regalos_6.jpeg',
      tags: [],
    },
    {
      id: 118,
      name: 'Merengues Clásicos',
      price: '$1.200',
      image: '/regalos_7.jpeg',
      tags: [],
    },
    {
      id: 119,
      name: 'Merengues de Colores',
      price: '$1.400',
      image: '/regalos_8.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 120,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/regalos_9.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 121,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/regalos_10.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 122,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/regalos_11.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 123,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/regalos_12.jpeg',
      tags: ['Nuevo'],
    },
    {
      id: 124,
      name: 'Macarons Franceses',
      price: '$2.200',
      image: '/regalos_13.jpeg',
      tags: ['Nuevo'],
    },
  ],
};

export const categoryInfo = {
  tortas_cumpleaños: {
    title: 'Tortas de Cumpleaños',
    description: 'Tortas artesanales para cada ocasión especial',
    color: '#FFD1DC',
  },
  tortas_postres: {
    title: 'Tortas Postres',
    description: 'Pequeñas delicias perfectas para compartir',
    color: '#FFDAB9',
  },
  tortas_bodas: {
    title: 'Tortas de Bodas',
    description: 'Elegancia y sabor para tu día inolvidable',
    color: '#E0FFFF',
  },
  tortas_infantiles: {
    title: 'Tortas Infantiles',
    description: 'Diseños divertidos que encantarán a los más pequeños',
    color: '#FFFACD',
  },
  tortas_grados: {
    title: 'Tortas de Grados',
    description: 'Celebraciones especiales con sabor único',
    color: '#FFFACD',
  },
  tortas_bautizos: {
    title: 'Tortas de Bautizos',
    description: 'Dulces momentos para celebrar bautizos',
    color: '#FFFACD',
  },
  otros: {
    title: 'Otras Tortas',
    description: 'Variedad de opciones para todos los gustos',
    color: '#F0E68C',
  },
  regalos: {
    title: 'Regalos Dulces',
    description: 'Galletas crujientes con ingredientes premium',
    color: '#E6E6FA',
  },
  mesas_dulces: {
    title: 'Mesas Dulces',
    description: 'Deliciosas mesas para tus eventos especiales',
    color: '#E6E6FA',
  }
};